#!/bin/bash

python="python3"
pipurl="https://bootstrap.pypa.io/get-pip.py"
poetryurl="https://install.python-poetry.org"
poetrygiturl="https://github.com/python-poetry/poetry.git"

if [[ -n "${USEPYTHON}" ]]; then
    python="${USEPYTHON}"
    if [[ $("${python}" --version) =~ "Python 2" ]]; then
        pipurl="https://bootstrap.pypa.io/pip/2.7/get-pip.py"
    fi
fi

if [[ $(basename "${SHELL}") != "bash" ]]; then
    echo "I need bash" 1>&2
    exit 1
fi
basedir=$(readlink -f $(dirname $(readlink -f "${BASH_SOURCE[0]}"))/..)
me=$(basename "${basedir}")

if [[ -z "${DEV}" ]]; then
    DEV="--without dev"
else
    DEV=""
fi

if [[ ! -z "${EXTRAS}" ]]; then
    EXTRAS="--extras \"${EXTRAS}\""
fi

export PS1="(${me}-bash) ${PS1}"
export PYTHONUSERBASE="${basedir}/.poetryinst"
[[ ! -d "${PYTHONUSERBASE}" ]] && mkdir -p "${PYTHONUSERBASE}"
export PIP_CACHE_DIR="${PYTHONUSERBASE}/pipcache"
export PROJECT_HOME="${PYTHONUSERBASE}/poetry"
export POETRY_HOME="${PROJECT_HOME}"
export POETRY_CACHE_DIR="${PROJECT_HOME}"
export POETRY_CONFIG_DIR="${PROJECT_HOME}"
export PYTHONPATH="${basedir}${PYTHONPATH:+:${PYTHONPATH}}"
export PATH="${PROJECT_HOME}/bin:${PYTHONUSERBASE}/bin:${PATH}"
[[ ! "$(type -P pip)" =~ "${PYTHONUSERBASE}" ]] && { curl -sSL "${pipurl}" | "${python}" -; }
[[ ! "$(type -P pip)" =~ "${PYTHONUSERBASE}" ]] && { echo "failed to install pip" 1>&2; exit 1; }
[[ ! "$(type -P poetry)" =~ "${PYTHONUSERBASE}" ]] && { curl -sSL "${poetryurl}" | "${python}" - --git "${poetrygiturl}" ; }
(cd "${basedir}"; (eval poetry install "${DEV}" "${EXTRAS}") || { echo "failed to install dependencies" 1>&2; exit 1; })
(cd "${basedir}" && "${@}")