[project]
name = 'tools-for-wiki'
description = 'tools for wiki'
version = '0.0.1'
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"pywikibot",
"pypdf"
]

[tool.uv]
dev-dependencies = [
    "basedpyright>=1.17.5",
]
